export const SEED_INGREDIENTS = [
  { name: 'Tomato', emoji: '🍅' },
  { name: 'Avocado', emoji: '🥑' },
  { name: 'Chocolate', emoji: '🍫' },
  { name: 'Burrata', emoji: '🧀' },
  { name: 'Nuts', emoji: '🥜' },
  { name: 'Cucumber', emoji: '🥒' },
  { name: 'Strawberry', emoji: '🍓' },
  { name: 'Basil', emoji: '🌿' },
  { name: 'Lemon', emoji: '🍋' },
  { name: 'Honey', emoji: '🍯' },
  { name: 'Garlic', emoji: '🧄' },
  { name: 'Banana', emoji: '🍌' },
  { name: 'Bacon', emoji: '🥓' },
  { name: 'Egg', emoji: '🥚' },
  { name: 'Bread', emoji: '🍞' },
  { name: 'Coffee', emoji: '☕' },
  { name: 'Pepper', emoji: '🌶️' },
  { name: 'Onion', emoji: '🧅' },
  { name: 'Mango', emoji: '🥭' },
  { name: 'Coconut', emoji: '🥥' },
];
